// Shared contract between the agent-key layer, the MCP server, and the UI.
//
// This file is the seam: it defines the types each side codes against so the
// auth implementation, the tool implementations, and the settings UI can be
// built independently. It holds types and constants only — no logic, no imports
// from the database or from Next.js, so it is safe to import from anywhere.

import type { ModelId, Quality } from "@/lib/types";

/** What an agent key is permitted to do. Keys default to "generate" alone. */
export type AgentScope = "generate" | "delete" | "publish" | "templates";

export const ALL_AGENT_SCOPES: AgentScope[] = ["generate", "delete", "publish", "templates"];
export const DEFAULT_AGENT_SCOPES: AgentScope[] = ["generate"];

/**
 * Where a key may write.
 * - own    — a workspace created for this key; nowhere else. The default.
 * - pinned — one existing workspace chosen by the user; nowhere else.
 * - any    — any workspace the owner has, chosen per call.
 */
export type DestinationMode = "own" | "pinned" | "any";

/** How a user's generations are billed. See lib/credentialStore.ts. */
export type CredentialAccess = "own" | "shared" | "none";

/** Key prefix. The full token is `hf_live_<43 chars of base64url>`. */
export const AGENT_KEY_PREFIX = "hf_live_";
/** Bytes of entropy behind the token. */
export const AGENT_KEY_BYTES = 32;
/** Characters of the token retained for display, including the prefix. */
export const AGENT_KEY_DISPLAY_CHARS = 16;
/** Default lifetime of a newly minted key, in days. */
export const DEFAULT_KEY_TTL_DAYS = 90;

/** Caps on what a key may create. Null means unrestricted. */
export interface AgentLimits {
  maxQuality: Quality | null;
  maxModel: ModelId | null;
  dailyImageLimit: number | null;
}

/**
 * The authenticated agent principal, returned by requireAgentKey().
 *
 * This is deliberately NOT the same shape as the session principal returned by
 * requireAuth(). An agent key is its own kind of caller: it carries no role, so
 * it can never satisfy requireAdmin(), whatever the account that minted it.
 */
export interface AgentPrincipal {
  kind: "agent";
  keyId: string;
  /** The user this key acts for. All data access is scoped to this id. */
  userId: string;
  /** Display name of the key, snapshotted onto every image it creates. */
  label: string;
  scopes: AgentScope[];
  destinationMode: DestinationMode;
  /** Resolved workspace id, or null meaning the user's Main workspace. */
  defaultWorkspaceId: string | null;
  limits: AgentLimits;
  /** Images already generated by this key today (UTC). */
  usedToday: number;
}

/** Why an agent request was refused. Maps onto MCP tool errors and HTTP codes. */
export type AgentDenialReason =
  | "missing_token"
  | "malformed_token"
  | "unknown_key"
  | "revoked"
  | "expired"
  | "account_missing"
  | "account_unapproved"
  | "missing_scope"
  | "workspace_forbidden"
  | "quality_exceeds_limit"
  | "model_exceeds_limit"
  | "daily_limit_reached"
  | "no_credentials";

export interface AgentDenial {
  kind: "denied";
  reason: AgentDenialReason;
  /** Human-readable, safe to surface to the agent and to the user. */
  message: string;
  /** HTTP status the MCP route should answer with. */
  status: 401 | 403 | 429;
}

export type AgentAuthResult = AgentPrincipal | AgentDenial;

export function isDenial(r: AgentAuthResult): r is AgentDenial {
  return (r as AgentDenial).kind === "denied";
}

/** Ordered weakest to strongest, for ceiling comparisons. */
export const QUALITY_RANK: Record<Quality, number> = {
  "512": 0,
  "1K": 1,
  "2K": 2,
  "4K": 3,
};

/** Ordered cheapest to most expensive, for ceiling comparisons. */
export const MODEL_RANK: Record<ModelId, number> = {
  "gemini-3.1-flash-lite-image": 0,
  "gemini-3.1-flash-image": 1,
  "gemini-3-pro-image": 2,
};

export function qualityWithinLimit(requested: Quality, limit: Quality | null): boolean {
  if (!limit) return true;
  return QUALITY_RANK[requested] <= QUALITY_RANK[limit];
}

export function modelWithinLimit(requested: ModelId, limit: ModelId | null): boolean {
  if (!limit) return true;
  return MODEL_RANK[requested] <= MODEL_RANK[limit];
}

/** Provenance written onto every image an agent creates. */
export interface AgentProvenance {
  origin: "agent";
  agentKeyId: string;
  agentLabel: string;
}

export function provenanceFor(principal: AgentPrincipal): AgentProvenance {
  return { origin: "agent", agentKeyId: principal.keyId, agentLabel: principal.label };
}

/** UTC day key used by the api_key_usage table. */
export function utcDayKey(now: number): string {
  return new Date(now).toISOString().slice(0, 10);
}

// ── Credential resolution seam ───────────────────────────────────────────────
// Implemented in lib/credentialStore.ts. Declared here so the generation path
// can be written against it before per-user credentials land.

export type CredentialSourceKind = "user" | "instance" | "env" | "none";

export interface ResolvedCredentials {
  /** A ServiceAccount from lib/vertexAuth, or null when generation is unavailable. */
  sa: import("@/lib/vertexAuth").ServiceAccount | null;
  source: CredentialSourceKind;
  /** The owning user's access tier at resolution time. */
  access: CredentialAccess;
  /**
   * Stable identity of the credential, used to key the Vertex access-token
   * cache. Without this, per-user service accounts collide on a single global
   * token and generations bill to whoever authenticated first.
   */
  cacheKey: string;
}
