services:
  homefield:
    image: ghcr.io/stink-o/homefield:latest
    container_name: homefield
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./homefield.env
    volumes:
      - ./storage:/app/storage
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
