"use client";

import { Bot } from "lucide-react";
import { AGENT_CHIP, AGENT_CHIP_ON_IMAGE } from "./agentTheme";

interface AgentBadgeProps {
  /** The agent's name, snapshotted onto the image when it was generated. */
  label: string;
  /** Sitting on top of an image rather than on an app surface. */
  onImage?: boolean;
  /**
   * Drop the text on very narrow cards, leaving the icon. Only meaningful
   * inside a `@container`, which is why it is opt-in.
   */
  compactLabel?: boolean;
  className?: string;
}

export default function AgentBadge({ label, onImage = false, compactLabel = false, className = "" }: AgentBadgeProps) {
  return (
    <span
      className={`inline-flex max-w-[140px] items-center gap-1 rounded px-1.5 py-0.5 text-[10px] font-medium ${
        onImage ? AGENT_CHIP_ON_IMAGE : AGENT_CHIP
      } ${className}`}
      title={`Generated by ${label}`}
    >
      <Bot size={10} className="shrink-0" />
      <span className={`truncate ${compactLabel ? "hidden [@container(min-width:200px)]:inline" : ""}`}>
        {label}
      </span>
    </span>
  );
}
